#!/usr/bin/env python3
"""v55.89 — build the categorized world-train roster JS from the sprite crop manifest CSV.

Reads assets/train/train char world/index/train_sprite_crop_manifest_1_275.csv and emits
games/data/train-world.js → window.TRAIN_WORLD = { categories:[{key,name,emoji,color,desc,trains:[...]}] }

Each train: { key:'w001', idx, name, model, year, sub, emoji, isCharacter:true,
  spriteUrl:'../assets/train/world/NNN.webp', faces:'left'  (engine mirrors → faces RIGHT),
  kmh, baseSpeed, boostMult, boostDur, bodyColor, accColor }

Categories (so the picker isn't one giant page): Uap Klasik / Uap Modern / Diesel / Listrik /
Kereta Cepat / Komuter & Tram / Indonesia (251-275). Indonesia overrides type.
"""
import csv, json, os

CSV = "assets/train/train char world/index/train_sprite_crop_manifest_1_275.csv"
OUT = "games/data/train-world.js"

CATS = [
    ("uap_klasik", "Uap Klasik 🚂", "🚂", "#b08968", "Lokomotif uap paling tua (1804–1899) — awal mula kereta api."),
    ("uap_modern", "Uap Modern 🚂", "🚂", "#9a6a4a", "Raksasa uap 1900–1960an — Big Boy, Mallard, Flying Scotsman."),
    ("diesel",     "Diesel 🛲",     "🛲", "#6b7280", "Lokomotif diesel — bertenaga mesin, era 1950an ke atas."),
    ("listrik",    "Listrik ⚡",    "⚡", "#2563eb", "Lokomotif listrik — cepat, bersih, kabel di atas."),
    ("cepat",      "Kereta Cepat 🚄", "🚄", "#dc2626", "Shinkansen, TGV, ICE, Maglev — kereta tercepat di dunia!"),
    ("komuter",    "Komuter & Tram 🚉", "🚉", "#0891b2", "KRL, EMU, tram, LRT — kereta penumpang sehari-hari."),
    ("indonesia",  "Indonesia 🇮🇩", "🇮🇩", "#16a34a", "Kereta Indonesia — C12 & D52 heritage sampai KRL, LRT & Whoosh!"),
]

# per-category gameplay tuning: (kmh_lo, kmh_hi displayed, baseSpeed kept balanced 1.7-2.1)
TUNE = {
    "uap_klasik": (25, 55, 1.70), "uap_modern": (55, 130, 1.85), "diesel": (95, 150, 1.95),
    "listrik": (110, 175, 2.00), "cepat": (250, 430, 2.10), "komuter": (80, 140, 1.92),
    "indonesia": (60, 350, 1.95),
}

def classify(idx, year, mt):
    m = (mt or "").lower()
    if idx >= 251:
        return "indonesia"
    if "maglev" in m or "high-speed" in m or "high speed" in m or "bullet" in m:
        return "cepat"
    if any(k in m for k in ["multiple unit", " emu", "emu", " dmu", "dmu", "railcar", "railmotor", "tram", "light rail"]):
        return "komuter"
    if "diesel" in m or "gas turbine" in m:
        return "diesel"
    if "electric locomotive" in m or ("electric" in m and "locomotive" in m):
        return "listrik"
    # steam / geared / rack / compound / articulated → steam, split by year
    return "uap_klasik" if (year and year < 1900) else "uap_modern"

def main():
    rows = []
    with open(CSV, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append(r)
    buckets = {k: [] for k, *_ in CATS}
    for r in rows:
        idx = int(r["index"]); year = int(r["year"]) if r["year"] else 0
        name = r["name"].strip(); model = r["model_type"].strip()
        cat = classify(idx, year, model)
        lo, hi, bs = TUNE[cat]
        # deterministic per-index spread (no RNG) across the displayed kmh band
        span = max(1, hi - lo)
        kmh = lo + (idx * 37) % span
        baseSpeed = round(bs + ((idx % 5) - 2) * 0.03, 3)   # ±0.06 tiny variety, balanced
        buckets[cat].append({
            "key": f"w{idx:03d}", "idx": idx, "name": name, "model": model, "year": year,
            "sub": f"{model} · {year}" if year else model, "emoji": "🚆",
            "isCharacter": True, "spriteUrl": f"../assets/train/world/{idx:03d}.webp",
            "faces": "left", "kmh": kmh, "baseSpeed": baseSpeed, "boostMult": 1.5, "boostDur": 1500,
            "bodyColor": "#475569", "accColor": "#cbd5e1",
        })
    categories = []
    for key, name, emoji, color, desc in CATS:
        ts = sorted(buckets[key], key=lambda t: t["idx"])
        categories.append({"key": key, "name": name, "emoji": emoji, "color": color,
                           "desc": desc, "trains": ts})
        print(f"{key:12s} {len(ts):3d} trains")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    payload = {"categories": categories}
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* v55.89 — AUTO-GENERATED by tools/build-train-world.py from the sprite crop\n")
        f.write(" * manifest CSV. 275 world trains, categorized for the g14 picker. Do not hand-edit;\n")
        f.write(" * re-run the tool. faces:'left' → the game/picker mirror to face RIGHT. */\n")
        f.write("window.TRAIN_WORLD = " + json.dumps(payload, ensure_ascii=False, indent=0) + ";\n")
    print(f"\n→ {OUT}  ({sum(len(b) for b in buckets.values())} trains total)")

if __name__ == "__main__":
    main()
