#!/usr/bin/env python3
"""A-322 — build the museum lore roster from the master sprite index Markdown table.

Reads  assets/train/train char world/index/train_sprite_database_index_1_275.md
        (pipe table: | Index | Year | Name | Model / Type | Notes / Livery Reference |)
Writes  games/data/museum-lore.js
        window.MUSEUM_LORE = { "1": {"year":1804,"name":"...","type":"...","note":"..."}, ... };

Robust: splits on '|', skips the header + separator rows, trims cells, keeps accented
UTF-8 chars, rejoins any stray '|' back into the note. Idempotent / re-runnable.
Produces exactly 275 keys (1..275).
"""
import json
import os
import re
import sys

MD = "assets/train/train char world/index/train_sprite_database_index_1_275.md"
OUT = "games/data/museum-lore.js"


def parse_int(s):
    m = re.search(r"-?\d+", s or "")
    return int(m.group()) if m else None


def main():
    if not os.path.exists(MD):
        sys.exit(f"! source not found: {MD}")
    lore = {}
    with open(MD, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("|"):
                continue
            # strip leading/trailing pipe, split; rejoin any stray pipe into the note col
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) < 5:
                continue
            idx = parse_int(cells[0])
            if idx is None:
                continue  # header ("Index") or separator ("---") rows
            year = parse_int(cells[1])
            name = cells[2].strip()
            typ = cells[3].strip()
            note = "|".join(cells[4:]).strip()  # keep any pipe that lived inside notes
            if not name:
                continue
            lore[str(idx)] = {
                "year": year if year is not None else 0,
                "name": name,
                "type": typ,
                "note": note,
            }

    keys = sorted(int(k) for k in lore)
    if not keys:
        sys.exit("! parsed 0 rows — check the table format")
    missing = [i for i in range(1, keys[-1] + 1) if str(i) not in lore]
    if missing:
        print(f"! WARNING missing indices: {missing[:20]}{' …' if len(missing) > 20 else ''}")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    ordered = {str(k): lore[str(k)] for k in keys}
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* A-322 — AUTO-GENERATED by tools/build-museum-lore.py from the master\n")
        f.write(" * train sprite index (train_sprite_database_index_1_275.md). Do not hand-edit;\n")
        f.write(" * re-run the tool. Keyed by 1..275 world-sprite index → real year/name/type/note. */\n")
        f.write("window.MUSEUM_LORE = " + json.dumps(ordered, ensure_ascii=False, indent=0) + ";\n")
    print(f"→ {OUT}  ({len(ordered)} lore entries, indices {keys[0]}..{keys[-1]})")


if __name__ == "__main__":
    main()
