#!/usr/bin/env python3
"""Regenerate games/data/train-sprites.js (the TrainSprites helper's metadata table) from assets/db/index.json.

    python3 tools/gen-train-sprites-js.py          # rewrite the file
    python3 tools/gen-train-sprites-js.py --check  # exit 1 when the file is stale

The database (index.json, category `train-char`) stays the single source of truth; this table only lets a game ask
"Linus facing east, happy, top view" without loading the whole index. Runs after tools/ingest-train-sprites.py.
"""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'games' / 'data' / 'train-sprites.js'

HEAD = r'''/* GENERATED by tools/gen-train-sprites-js.py from assets/db/index.json (category train-char) - do not edit.
 * window.TrainSprites: ask the shared sprite database for a train by CHARACTER + HEADING + VIEW + EXPRESSION
 * instead of hard-coding file names.
 *
 *   TrainSprites.pick('linus', {facing: 'e' | 90, view: 'top' | 'side' | 'front' | 'rear' | 'any', expression: 'happy'})
 *       -> db key ('train-char/linus/top-e'), or null for an unknown character. Always falls back to the nearest
 *          heading / the neutral expression, so a missing view never throws.
 *   TrainSprites.info(key)   -> {char, name, view, facing, expression, w, h, anchor:[x,y], baseline, alt, derived}
 *   TrainSprites.src(key)    -> base-path aware URL (AssetIndex.path when loaded)
 *   TrainSprites.missing(ch) -> names the sheet did not draw natively (top views derived by flip/turn are listed)
 *   TrainSprites.chars() / TrainSprites.list(ch)
 * facing = compass degrees the NOSE points: 0 up the screen / away from camera, 90 right, 180 toward camera, 270 left.
 * view groups: top | side (side-l, side-r) | front (front, front-34l, front-34r) | rear (rear, rear-34l, rear-34r).
 */
(function () {
  var W = typeof window !== 'undefined' ? window : globalThis
  if (W.TrainSprites) return
'''
TAIL = r'''
  var CAT = 'train-char/'
  var COMPASS = { n: 0, ne: 45, e: 90, se: 135, s: 180, sw: 225, w: 270, nw: 315 }
  var GROUP = { top: ['top'], side: ['side'], front: ['front', 'front34'], rear: ['rear', 'rear34'], any: ['top', 'side', 'front', 'front34', 'rear', 'rear34'] }
  function deg (f) {
    if (typeof f === 'string') f = COMPASS[f.toLowerCase()] != null ? COMPASS[f.toLowerCase()] : parseFloat(f)
    f = +f || 0
    return ((f % 360) + 360) % 360
  }
  function gap (a, b) { var d = Math.abs(a - b) % 360; return d > 180 ? 360 - d : d }
  function rec (ch, r) {
    return { char: ch, name: r[0], key: CAT + ch + '/' + r[0], view: r[1], facing: r[2], expression: r[3], alt: !!r[4], derived: !!r[5],
      w: r[6], h: r[7], anchor: [r[8], r[9]], baseline: r[10] }
  }
  var BYKEY = {}
  Object.keys(DATA).forEach(function (ch) { DATA[ch].keys = DATA[ch].rows.map(function (r) { var o = rec(ch, r); BYKEY[o.key] = o; return o }) })
  function pick (ch, o) {
    var d = DATA[ch]
    if (!d) return null
    o = o || {}
    var view = o.view || 'top', groups = GROUP[view] || GROUP.any, want = deg(o.facing), expr = o.expression || 'neutral'
    var pool = d.keys.filter(function (r) { return groups.indexOf(r.view) >= 0 })
    if (!pool.length) pool = d.keys.filter(function (r) { return r.view === 'top' })
    var best = null, bs = 1e9
    pool.forEach(function (r) {
      var s = gap(r.facing, want) * 10 + (r.alt ? 5 : 0) + (r.derived ? 1 : 0) + (r.expression === expr ? 0 : (r.expression === 'neutral' ? 40 : 60))
      if (view === 'top' && r.alt) s += 500
      if (s < bs) { bs = s; best = r }
    })
    return best ? best.key : null
  }
  function base () { try { return location.pathname.indexOf('/Dunia-Emosi/') === 0 ? '/Dunia-Emosi/' : '/' } catch (e) { return '/' } }
  W.TrainSprites = {
    chars: function () { return Object.keys(DATA) },
    list: function (ch) { return DATA[ch] ? DATA[ch].keys.map(function (r) { return r.key }) : [] },
    pick: pick,
    info: function (key) { return BYKEY[key] || null },
    missing: function (ch) { return DATA[ch] ? DATA[ch].missing.slice() : [] },
    src: function (key) {
      var r = BYKEY[key]
      if (!r) return null
      if (W.AssetIndex && W.AssetIndex.path) { var p = W.AssetIndex.path(key); if (p) return p }
      return base() + 'assets/db/lib/' + key + '.webp'
    }
  }
})()
'''


def build():
    idx = json.loads((ROOT / 'assets' / 'db' / 'index.json').read_text(encoding='utf-8'))['assets']
    data = {}
    for key, e in sorted(idx.items()):
        if e.get('cat') != 'train-char' or 'missing' not in e:   # the playable trains with top-down sheets; cast cells (coach, caboose, Goro) have no top views
            continue
        ch = e['char']
        d = data.setdefault(ch, {'missing': e['missing'], 'rows': []})
        name = key.split('/', 2)[2]
        d['rows'].append([name, e['view'], e['facing'], e['expression'], int(e['alt']), int(e['derived']),
                          e['w'], e['h'], e['anchor'][0], e['anchor'][1], e['baseline']])
    body = '  var DATA = ' + json.dumps(data, separators=(',', ':')) + '\n'
    return HEAD + body + TAIL


if __name__ == '__main__':
    text = build()
    if '--check' in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text(encoding='utf-8') == text else 1)
    OUT.write_text(text, encoding='utf-8')
    print('wrote', OUT, len(text), 'bytes')
