#!/usr/bin/env python3
"""Generate games/data/kereta-cast.js: which story-cast sprite appears in which scenario, with the owner's OFFICIAL
Indonesian display names (name_id from assets/db/index.json). `--check` exits 1 when the file is stale.
The Malivlak table uses EVERY malivlak-char sprite; the Brave table follows the storyline notes."""
import json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'games' / 'data' / 'kereta-cast.js'
M = 'malivlak-char/'
MALIVLAK = {
 1: [M+'petugas-stasiun/berdiri', M+'penumpang-jas-kotak/jam-saku', M+'penumpang-ungu/berdiri'],
 2: [M+'petugas-bagasi/koper-besar', M+'petugas-bagasi/angkat', M+'penumpang-ungu/koper'],
 3: [M+'petugas-stasiun/peluit', M+'petugas-stasiun/bendera-bawah'],
 4: [M+'masinis/jalan'], 5: [M+'masinis/pipa-2'],
 6: [M+'penumpang-ungu/lari-2', 'animal/kelinci/lompat', 'animal/kelinci/berdiri', M+'penumpang-ungu/lari'],
 7: [M+'masinis/ikan', 'animal/ikan/kanan', 'animal/ikan/samping'],
 8: [M+'penumpang-ungu/duduk', 'animal/kelinci/jongkok', 'animal/kelinci/duduk-belakang'],
 9: [M+'masinis/terkejut', M+'masinis/wajan'], 10: [M+'masinis/jalan'],
 11: ['animal/beruang/jalan', 'animal/beruang/depan', M+'masinis/terkejut'],
 12: ['animal/beruang/duduk', M+'penumpang-ungu/duduk'], 13: ['animal/beruang/belakang', M+'masinis/jalan'],
 14: [M+'masinis/palu', M+'masinis/periksa'],
 15: [M+'petugas-stasiun/berdiri', M+'orkes/pemimpin', M+'orkes/drum', M+'orkes/tuba', M+'orkes/terompet', M+'orkes/kontrabas'],
 16: [M+'petugas-stasiun/bendera', M+'penyambut/jangkung-bungkuk', M+'orkes/pemimpin-tongkat', M+'penyambut/jangkung'],
 17: [M+'petugas-stasiun/bendera-bawah', M+'penyambut/pendek'],
 18: [M+'pembaca-pidato/terkejut', M+'pembaca-pidato/kertas', M+'pembaca-pidato/gestur'],
 19: [M+'penyambut/pendek-medali', M+'masinis/medali', M+'orkes/pemimpin-kiri', M+'orkes/drum-angkat', M+'orkes/tuba-tekuk'],
 20: [M+'masinis/pipa', M+'penumpang-jas-kotak/jalan', M+'orkes/kontrabas-2', M+'orkes/terompet-atas'],
}
S = 'story-char/'
BRAVE = {
 1: [S+'henry/wave'], 2: [S+'henry/shovel'], 3: [S+'henry/point'], 4: [S+'henry/jongkok', 'animal/turtle/shell', S+'anak-kura/hold'],
 5: [S+'henry/wave', 'animal/bird-blue/fly'], 6: [S+'baron/angkuh', S+'baron/stand'], 7: [S+'baron/stand', S+'henry/worried'], 8: [S+'baron/angkuh', S+'henry/worried'],
 9: ['train-char/goro-loco/front-34l', S+'carter/hands-hips', S+'james/arms-folded'], 10: [S+'james/scroll', 'train-char/rongsokan-a/v2', 'train-char/rongsokan-b/v5', 'train-char/goro-loco/front-34r'],
 11: [S+'scarlet/ramah', S+'henry/worried', S+'scarlet/stand'], 12: [S+'baron/stand', S+'baron/angkuh'], 13: [S+'baron/angkuh', S+'katrina/stand'],
 14: [S+'carter/arms-crossed', S+'james/walk-scroll', S+'henry/worried'], 15: [S+'scarlet/cemas-atas', S+'baron/shocked'], 16: [S+'scarlet/cemas-atas', S+'henry/worried'],
 17: [S+'carter/point', 'train-char/goro-loco/front-34l'], 18: ['train-char/goro-loco/front-34r', S+'carter/surprised', 'animal/vulture/perch-1'], 19: [S+'james/point-scroll', S+'carter/defeated', 'train-char/goro-loco/front-34l'],
 20: [S+'henry/point', S+'katrina/khawatir'], 21: [S+'baron/stand', S+'katrina/stand', S+'henry/jongkok'], 22: [S+'henry/shovel', S+'katrina/shovel'],
 23: [S+'baron/shocked', S+'katrina/khawatir'], 24: [S+'henry/worried', S+'scarlet/worried'], 25: [S+'scarlet/worried', S+'henry/worried', S+'katrina/khawatir'],
 26: ['animal/deer/stand', 'animal/rabbit/sit', 'animal/bird-blue/fly', 'animal/cardinal/fly'], 27: [S+'mekanik/wave', S+'pelukis/stand', S+'anak-cat/stand', S+'henry/wave'],
 28: [S+'pelukis/thumbs', S+'anak-cat/kneel', S+'mekanik-wanita/hips', S+'nyonya-topi/cheer', S+'anak-kura/hug'], 29: ['train-char/coach-green/front-34l', 'train-char/caboose-red/front-34l', S+'tuan-merah/stand'],
 30: [S+'henry/wave', S+'scarlet/stand', S+'anak-kura/shy', 'train-char/caboose-red/front-34r', 'animal/deer/graze', 'animal/rabbit/run', 'animal/vulture/perch-2', 'animal/turtle/stand'],
 31: ['animal/deer/stand'], 32: ['train-char/coach-green/front-34l', 'train-char/caboose-red/front-34r', S+'mekanik/stand'], 33: [S+'henry/worried'], 34: [S+'henry/point', 'animal/rabbit/sit'],
}
HELLBENT = {}
def build():
    a = json.loads((ROOT / 'assets/db/index.json').read_text(encoding='utf-8'))['assets']
    keys = sorted({k for t in (MALIVLAK, BRAVE) for v in t.values() for k in v})
    miss = [k for k in keys if k not in a]
    if miss: raise SystemExit('cast keys not in the database: %s' % miss)
    names = {k: a[k].get('name_id') or a[k].get('char', k) for k in keys}
    body = 'window.KeretaCast = ' + json.dumps({'malivlak': MALIVLAK, 'brave': BRAVE, 'hellbent': HELLBENT, 'names': names}, ensure_ascii=False, separators=(',', ':')) + '\n'
    return '/* GENERATED by tools/gen-kereta-cast-js.py - do not edit. Scenario -> cast sprites (database keys) with the owner\'s official names (name_id). */\n' + body
if __name__ == '__main__':
    t = build()
    if '--check' in sys.argv: sys.exit(0 if OUT.exists() and OUT.read_text(encoding='utf-8') == t else 1)
    OUT.write_text(t, encoding='utf-8'); print('wrote', OUT)
