#!/usr/bin/env python3
"""v55.84 — measure each train sprite's WHEEL-BASELINE (the alpha opaque-bottom row, as a
ratio of sprite height) so g14 can anchor every loco EXACTLY on the rail line (zero
tolerance) instead of a generic 0.86 guess. Writes games/data/train-wheel-anchors.js
(window.TRAIN_WHEEL_ANCHORS = { 'thomas.webp': 0.991, ... }). Read-only on the art."""
import glob
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# v56.0 B-285/A3 — measure EVERY player-selectable sprite family, not just AEG:
# the 4 PROTECTED trains (assets/train/*-body.webp) and the 275 world trains had NO
# entries and fell back to a 0.99 anchor that hung wheels 1-2px below the rail.
SPRITE_DIRS = [
    os.path.join(ROOT, "assets/train/aeg"),
    os.path.join(ROOT, "assets/train"),        # caseyjr-body.webp etc. (top-level only)
    os.path.join(ROOT, "assets/train/world"),
]
OUT = os.path.join(ROOT, "games/data/train-wheel-anchors.js")


def opaque_bottom_ratio(path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    a = im.split()[3].load()
    bottom = h - 1
    for y in range(h - 1, -1, -1):
        if max(a[x, y] for x in range(0, w, 2)) > 16:
            bottom = y
            break
    # +1 so the ratio points at the row just below the last opaque pixel (wheel contact)
    return round(min(1.0, (bottom + 1) / h), 4)


def main():
    entries = {}
    low = []
    for d in SPRITE_DIRS:
        for f in sorted(glob.glob(os.path.join(d, "*.webp"))):
            key = os.path.basename(f)
            if key in entries:
                # basename collision across dirs — key by last two path segments so
                # g14WheelAnchor (which matches on basename) never gets the wrong value.
                key = "%s/%s" % (os.path.basename(d), os.path.basename(f))
            try:
                r = opaque_bottom_ratio(f)
            except Exception as e:  # unreadable art must not kill the whole run
                print("SKIP %s (%s)" % (f, e))
                continue
            entries[key] = r
            if r < 0.93:
                low.append((key, r))
    body = ",\n".join("  '%s': %s" % (k, v) for k, v in sorted(entries.items()))
    js = (
        "/* games/data/train-wheel-anchors.js — AUTO-GENERATED by tools/measure-wheel-anchors.py\n"
        " * Per-sprite wheel-baseline ratio (alpha opaque-bottom / height) so g14 anchors every\n"
        " * loco's wheels EXACTLY on the rail line (zero tolerance). Keyed by sprite filename. */\n"
        "window.TRAIN_WHEEL_ANCHORS = {\n" + body + "\n};\n"
    )
    with open(OUT, "w") as fh:
        fh.write(js)
    print("wrote %s (%d sprites, ratio %.3f-%.3f)" % (
        OUT, len(entries), min(entries.values()), max(entries.values())))
    if low:
        print("EYEBALL these %d sprites (anchor < 0.93 — possible baked shadow / odd trim):" % len(low))
        for k, r in low:
            print("  %s = %s" % (k, r))


if __name__ == "__main__":
    main()
