#!/usr/bin/env python3
"""v55.84 — measure each train sprite's WHEEL-BASELINE (the alpha opaque-bottom row, as a
ratio of sprite height) so g14 can anchor every loco EXACTLY on the rail line (zero
tolerance) instead of a generic 0.86 guess. Writes games/data/train-wheel-anchors.js
(window.TRAIN_WHEEL_ANCHORS = { 'thomas.webp': 0.991, ... }). Read-only on the art."""
import glob
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AEG = os.path.join(ROOT, "assets/train/aeg")
OUT = os.path.join(ROOT, "games/data/train-wheel-anchors.js")


def opaque_bottom_ratio(path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    a = im.split()[3].load()
    bottom = h - 1
    for y in range(h - 1, -1, -1):
        if max(a[x, y] for x in range(0, w, 2)) > 16:
            bottom = y
            break
    # +1 so the ratio points at the row just below the last opaque pixel (wheel contact)
    return round(min(1.0, (bottom + 1) / h), 4)


def main():
    entries = {}
    for f in sorted(glob.glob(os.path.join(AEG, "*.webp"))):
        entries[os.path.basename(f)] = opaque_bottom_ratio(f)
    body = ",\n".join("  '%s': %s" % (k, v) for k, v in entries.items())
    js = (
        "/* games/data/train-wheel-anchors.js — AUTO-GENERATED by tools/measure-wheel-anchors.py\n"
        " * Per-sprite wheel-baseline ratio (alpha opaque-bottom / height) so g14 anchors every\n"
        " * loco's wheels EXACTLY on the rail line (zero tolerance). Keyed by sprite filename. */\n"
        "window.TRAIN_WHEEL_ANCHORS = {\n" + body + "\n};\n"
    )
    with open(OUT, "w") as fh:
        fh.write(js)
    print("wrote %s (%d sprites, ratio %.3f–%.3f)" % (
        OUT, len(entries), min(entries.values()), max(entries.values())))


if __name__ == "__main__":
    main()
